version: '3.3'
services:

  composer:
    build:
      context: .
      args:
        - DEPLOYMENT=production
    networks:
      internal:
    ports:
      - "9090:9090"
    command: [--test --lint]

networks:
  internal:
